// vue2/src/components/Navbar.vue
<template>
  <nav class="main-nav">
    <router-link v-if="!user" :to="{name: 'login'}">Login</router-link>
     <router-link v-if="!user" :to="{name: 'register'}">Register</router-link>
     <a v-for="u in uu" v-bind:key="u.name">{{u.name}}</a>
     <a v-if="user" @click="handleSubmit">LogOut</a>

    <router-link :to="{ name: 'Home' }">Projects</router-link>
    <router-link :to="{ name: 'AddProject' }">Add a New Project</router-link>
  </nav>


  
</template>

<script>
import axios from 'axios'
import {mapActions} from 'vuex';
import {mapGetters} from 'vuex';
export default {
data(){
  return {
user:localStorage.getItem('user')
  }
},
computed:{
/*      users(){
            return this.$store.state.users;
        }, */

/*      uu () {
    return this.$store.getters.uu
  }    */

         ...mapGetters([
            'uu'
        ]) , 



},

methods: {

    handleSubmit() {

       axios.post('http://127.0.0.1:3000/api/logout'
      ).then(user => {
        localStorage.removeItem('user');

        this.$router.push('/')
        this.$router.go()
      }).catch(err => console.log(err))

    }
}

}
</script>

// react_project/src/components/Navbar.js
import { Link } from "react-router-dom";
import axios from 'axios'
import { Trans, useTranslation } from "react-i18next";


const Navbar = () => {
const user = localStorage.getItem('user');

  const handleClick = () => {

    axios.post('http://localhost:4001/api/logout'
   ).then(() => {
     localStorage.removeItem('user');

     window.location.href="/"
    }).catch(err => console.log(err))

 }


 const { t, i18n } = useTranslation();

 const changeLanguage = (language) => {
   i18n.changeLanguage(language);
   localStorage.setItem('lan', language);
   localStorage.setItem('d', 'rtl');


 };


  return (
    <div> 
    <nav className="navbar">
      <Link to="/"><h1>Have Fun</h1></Link>
      <div className="links">
    { !user && <Link className="btn" to="/register">Register</Link>}
     { !user && <Link className="btn" to="/login">LogIn</Link>}
      { user && <Link className="btn" onClick={handleClick} to="/login">LogOut</Link>}
      <Link className="btn" to="/">Home</Link>

      {user && <Link className="btn" to="">{user}</Link>}


        <Link to="/create" style={{ 
          color: 'white', 
          backgroundColor: '#f1356d',
          borderRadius: '8px' 
        }}>New Post</Link>

      </div>

    </nav>

<div dir={localStorage.getItem('d')} className="App">
<button onClick={() => {changeLanguage("en") }}>EN</button>
<button onClick={() => { changeLanguage("ar")}}>AR</button>
<hr/>
<Trans i18nKey="description.part1">
</Trans>
<div>{t("description.part2")}</div>
</div>

</div>
  );
}
 
export default Navbar;
